plat/kvm: Implement stub of ukplat_stack_set_current_thread for arm64
This patch is to fix the compilation error when building arm64 kvm image
build/unikraft_kvm-arm64.o: In function `schedcoop_schedule':
lib/ukschedcoop/schedcoop.c:107: undefined reference to
`ukplat_stack_set_current_thread'

In commit 017fffd59ece ("plat/*: Set current thread on IRQ stack"), it
introduce ukplat_stack_set_current_thread on x86 to set the thread_addr
on cpu_intr_stack. There are no isolating stack for interrupt on arm64
up to now. So make an empty stub here.

Signed-off-by: Jia He <justin.he@arm.com>
Reviewed-by: Santiago Pagani <santiago.pagani@neclab.eu>