plat/kvm/x86: Fix build error due to missing `assert.h` header
Once the commit
dbfb886b5312 ("plat: Ensure IRQ's disabled in `ukplat_lcpu_halt_irq`")
got merged, a new build error appeared:
```
 E  /usr/bin/ld: /github/workspace/_helloworld/.unikraft/build/libkvmplat.o: in function `ukplat_lcpu_halt_irq':
 E  /github/workspace/plat/kvm/x86/lcpu.c:50: undefined reference to `UK_ASSERT'
 E  collect2: error: ld returned 1 exit status
```

This happened due to `uk/assert.h` not being included.

Github-Fixes: #980
Signed-off-by: Sergiu Moga <sergiu@unikraft.io>
Reviewed-by: Alexander Jung <alex@unikraft.io>
Reviewed-by: Marco Schlumpp <marco@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>
Tested-by: Unikraft CI <monkey@unikraft.io>
GitHub-Closes: #1017