plat: Implement tls stub for arm64
Without this patch, compiler will report:
unikraft/plat/common/include/tls.h:38:2: error: #error "For thread-local
storage support, add tls.h for current architecture."
 #error "For thread-local storage support, add tls.h for current architecture."
And arm64 kvm plat target will not be built.

Now I don't remove the pre-compilation #warn as follows in
arch/arm/arm64/include/uk/asm/tls.h because I thought arm64 tls implementation
should use tpidr_el1. I will do it in the future.
"#warning Thread-local storage has not been tested on aarch64!"

Signed-off-by: Jia He <justin.he@arm.com>
Reviewed-by: Santiago Pagani <santiago.pagani@neclab.eu>