plat/*/pal: Add extern "C" guard to ectx.h for C++ compatibility
The uk_pal_ectx_* functions in plat/native/pal and plat/xen/pal are
defined as static inline without an extern "C" guard. When these
headers are pulled into C++ code, the functions get C++ language
linkage, which conflicts with the extern "C" declarations in
ukpal/include/uk/pal/ectx.h and breaks the build for any C++
application:

  ukpal/include/uk/pal/ectx.h:63: error: conflicting declaration of
  'void uk_pal_ectx_sanitize(uk_pal_ectx*)' with 'C' linkage
  plat/native/pal/include/uk/plat/pal/ectx.h:28: note: previous
  declaration with 'C++' linkage

One path that reaches it is libcxxabi's cxa_guard.cpp, through
uk/syscall.h, uk/arch/ctx.h and uk/lcpu/ectx.h.

Tested by building helloworld-cpp on both stable and staging.

Signed-off-by: Radu Andrei Tudorica <raduandreitudorica3@gmail.com>