plat/common: arm: Include correct inline function __uk_test_and_clear_bit
As __uk_test_and_clear_bit has been moved to uk/bitops.h, the time.c could
not find this function from atomic.h. This will cause Arm64 build failed:

  LD      unikraft_kvm-arm64
/root/UF/unikraft/build/unikraft_kvm-arm64.o: In function `time_block_until':
:(.text+0x400): undefined reference to `__uk_test_and_clear_bit'
:(.text+0x400): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `__uk_test_and_clear_bit'
collect2: error: ld returned 1 exit status
/root/UF/unikraft/plat/kvm/Linker.uk:17: recipe for target '/root/UF/unikraft/build/unikraft_kvm-arm64' failed
make: *** [/root/UF/unikraft/build/unikraft_kvm-arm64] Error 1

Change atomic.h to bitops.h to solve this problem.

Signed-off-by: Wei Chen <wei.chen@arm.com>
Reviewed-by: Yuri Volchkov <yuri.volchkov@neclab.eu>