plat/kvm: Make VIRTIO_NET depend on VIRTIO_BUS
This is the setup to reproduce the bug:
Library Configuration -> enable uknetdev
Platform Configuration -> enable KVM guest:
	-> disable Virtio bus driver
	-> Virtio -> enable Virtio Net device

With this  setup, the following error occurs on build:
"undefined reference to ` _virtio_bus_register_driver'"

This fix solves the issue by enabling Virtio bus driver every time
Virtio Net device is enabled.

Signed-off-by: Teodora Serbanescu <teo.serbanescu16@gmail.com>
Signed-off-by: Andrei Gogonea <andrei.gogonea09@gmail.com>
Reviewed-by: Sharan Santhanam <sharan.santhanam@neclab.eu>